export { default as Home } from "./Home/Home";
export { default as RoomDetail } from "./RoomDetail/RoomDetail";
export { default as ViewMoreRoom } from "./Search/ViewMoreRoom";
export { default as SearchResult } from "./Search/SearchResult";
export { default as Login } from "./Login/Login";
export { default as Register } from "./SignUp/Register";
export { default as CreateRoom } from "./RoomManagement/CreateRoom";
export { default as Blog } from "./Blog";
export { default as BlogDetail } from "./Blog/blog-detail";
export { default as User } from "./User";
export {default as ChangePassword} from './User/ChangePassword';
export {default as LinkAccount} from './User/LinkAccount';